name: Factions
version: 1.8.2
main: com.massivecraft.factions.P
authors: [drtshock, externo6, Olof Cayorion Larsson, Brett Flannigan, Daniel Saukel]
softdepend: [PermissionsEx, Essentials, EssentialsChat, Vault, Spout, WorldEdit, WorldGuard, CombatTag]
commands:
  factions:
    description: The Factions base command
    aliases: [f]
api-version: 1.13
permissions:
# -------------------------------------------- #
# THE REAL NODES
# -------------------------------------------- #
  factions.access: {description: accordez l'accès au territoire à votre faction, avec le fperm approprié}
  factions.access.any: {description: accorder l'acces au territoire pour n importe quelle faction}
  factions.access.view: {description: voir les informations des accès à votre territoire}
  factions.adminmode: {description: activer le mode admin}
  factions.autoclaim: {description: permet de claim automatiquement}
  factions.cape: {description: manage faction capes}
  factions.cape.get: {description: get faction cape}
  factions.cape.set: {description: set faction cape}
  factions.cape.remove: {description: remove faction cape}
  factions.claim: {description: permet de claim à l'endroit ou vous vous trouvez}
  factions.claim.radius: {description: permet de claim avec un radus}
  factions.config: {description: changer les paramètres}
  factions.create: {description: creer une nouvelle faction}
  factions.deinvite: {description: ne plus inviter un joueur}
  factions.demote: {description: retrograder une personne de votre faction}
  factions.description: {description: changer le description de faction}
  factions.disband: {description: dissoudre une faction}
  factions.flag: {description: voir les flags d'une faction}
  factions.flag.set: {description: définir les flags}
  factions.help: {description: voir la page d'aide}
  factions.home: {description: teleporter au home de faction}
  factions.invite: {description: inviter une joueur dans votre faction}
  factions.join: {description: rejoindre une faction}
  factions.join.any: {description: rejoindre n'importe quelle faction, en contournant le processus d'invitation pour les factions fermées}
  factions.join.others: {description: specify another player in the join command, to move them to the specified faction}
  factions.kick: {description: exclure un joueur de votre faction}
  factions.leader: {description: hand over leader rights}
  factions.leader.any: {description: give or revoke leader status for any player in any faction}
  factions.leave: {description: quitter votre faction}
  factions.list: {description: Voir la liste de des factions}
  factions.lock: {description: }
  factions.map: {description: voir les territoires sur la map}
  factions.money.balance: {description: montre le solde actuel d'une factions}
  factions.money.balance.any: {description: show money balance for factions other than your own}
  factions.money.deposit: {description: ajouter de la money dans votre faction}
  factions.money.f2f: {description: transfer money from faction to faction}
  factions.money.f2p: {description: transfer money from faction to player}
  factions.money.p2f: {description: transfer money from player to faction}
  factions.money.withdraw: {description: retirer de l'argent de la banque de votre faction}
  factions.officer: {description: donner ou révoquer le rôle modérateur}
  factions.officer.any: {description: give or revoke officer rights for any player in any faction}
  factions.open: {description: changer si une invitation est requise pour rejoindre}
  factions.perm: {description: changer les permission faction}
  factions.power: {description: voir les power d'un joueur}
  factions.power.any: {description: voir le power des autres joueurs}
  factions.powerboost: {description: ajouter du boots à une faction}
  factions.promote: {description: promouvoir une personne de votre faction}
  factions.relation: {description: définir le souhait de relation avec une autre faction}
  factions.reload: {description: rafraichir les données du disque}
  factions.save: {description: sauvegarder toutes les données}
  factions.seechunk: {description: voir le chunk ou vous vous trouvez}
  factions.sethome: {description: mettre le home de faction}
  factions.show: {description: voir les informations d'une faction}
  factions.tag: {description: changer le nom de faction}
  factions.title: {description: mettre ou enlever le titre d'un joueur}
  factions.unclaim: {description: permet d'unclaim le territoire ou vous etes}
  factions.unclaimall: {description: unclaim tous les territoires de votre faction}
  factions.version: {description: voir le version du plugin}
# -------------------------------------------- #
# STAR NOTATION
# -------------------------------------------- #
  factions.cape.*:
    children:
      factions.cape.get: true
      factions.cape.set: true
      factions.cape.remove: true
  factions.money.*:
    children:
      factions.money.balance: true
      factions.money.balance.any: true
      factions.money.deposit: true
      factions.money.f2f: true
      factions.money.f2p: true
      factions.money.p2f: true
      factions.money.withdraw: true
# -------------------------------------------- #
# KITS
# -------------------------------------------- #
  factions.kit.admin:
    description: All faction permissions.
    children:
      factions.kit.mod: true
      factions.config: true
      factions.lock: true
      factions.reload: true
      factions.save: true
  factions.*:
    description: This is just an alias for factions.kit.admin
    children:
      factions.kit.admin: true
  factions.kit.mod:
    description: All faction permissions but configuration and persistance.
    children:
      factions.kit.halfmod: true
      factions.flag.set: true
      factions.powerboost: true
      factions.join.any: true
      factions.join.others: true
      factions.leader.any: true
      factions.officer.any: true
      factions.access.any: true
  factions.kit.halfmod:
    description: Can use adminmode and chat spy
    children:
      factions.kit.fullplayer: true
      factions.adminmode: true
  factions.kit.fullplayer:
    description: Can also create new factions.
    children:
      factions.kit.halfplayer: true
      factions.create: true
  factions.kit.halfplayer:
    description: Can do all but create factions.
    children:
      factions.access: true
      factions.access.view: true
      factions.autoclaim: true
      factions.cape: true
      factions.cape.*: true
      factions.claim: true
      factions.claim.radius: true
      factions.deinvite: true
      factions.demote: true
      factions.description: true
      factions.disband: true
      factions.flag: true
      factions.help: true
      factions.home: true
      factions.invite: true
      factions.join: true
      factions.kick: true
      factions.leader: true
      factions.leave: true
      factions.list: true
      factions.map: true
      factions.money.*: true
      factions.open: true
      factions.perm: true
      factions.power: true
      factions.power.any: true
      factions.promote: true
      factions.relation: true
      factions.seechunk: true
      factions.sethome: true
      factions.show: true
      factions.tag: true
      factions.title: true
      factions.unclaim: true
      factions.unclaimall: true
      factions.version: true
